const axios = require('axios');

// --- LOCAL FALLBACK LOGIC ---
function generateFallbackProfile(answers) {
    const answerString = JSON.stringify(answers).toLowerCase();

    // Simple keyword counting to determine style
    const traits = {
        warmth: (answerString.match(/touch|cuddle|hold|close|physical|warm/g) || []).length,
        logic: (answerString.match(/solve|help|act|do|fix|service/g) || []).length,
        depth: (answerString.match(/soul|deep|meaning|time|talk|listen/g) || []).length,
        fun: (answerString.match(/adventure|laugh|joke|play|travel/g) || []).length
    };

    // Determine dominant trait
    const dominant = Object.keys(traits).reduce((a, b) => traits[a] > traits[b] ? a : b);

    // Pre-written profiles for each dominant trait
    const profiles = {
        warmth: {
            color: { hex: "#FF6F61", name: "Living Coral", meaning: "A vibrant, nurturing hue that represents your need for connection and physical closeness." },
            profile: "You are a tactile lover who speaks through presence and touch.",
            primary: "Physical Touch & Closeness",
            secondary: "Words of Affirmation",
            insight: "You are the fireplace in a cold room; your love is felt as a physical warmth."
        },
        logic: {
            color: { hex: "#4A90E2", name: "Tranquil Azure", meaning: "A calm, reliable blue reflecting your steady and supportive nature." },
            profile: "You love by doing. For you, love is a verb, shown through support and reliability.",
            primary: "Acts of Service",
            secondary: "Quality Time",
            insight: "You are the anchor in the storm; your love is safety and consistency."
        },
        depth: {
            color: { hex: "#6B5B95", name: "Mystic Violet", meaning: "A deep, complex shade symbolizing your desire for soul-deep understanding." },
            profile: "You crave deep emotional intimacy and being truly 'seen' by your partner.",
            primary: "Quality Time & Deep Talk",
            secondary: "Physical Touch",
            insight: "You are the deep ocean; your love is vast, mysterious, and all-encompassing."
        },
        fun: {
            color: { hex: "#F7CAC9", name: "Playful Quartz", meaning: "A light, joyful pink representing your adventurous and spontaneous spirit." },
            profile: "You bring light and laughter into relationships. Love should be an adventure.",
            primary: "Shared Experiences",
            secondary: "Words of Affirmation",
            insight: "You are the spark; your love is energy, motion, and light."
        }
    };

    const result = profiles[dominant] || profiles.warmth; // Default to warmth if unsure

    return {
        loveProfile: result.profile,
        primaryLoveStyle: result.primary,
        secondaryLoveStyle: result.secondary,
        personalColor: result.color,
        strengths: "You give love generously and intuitively, often knowing what your partner needs before they ask.",
        challenges: "You may sometimes feel unappreciated if your specific love language isn't reciprocated.",
        communicationStyle: "You communicate best when you feel safe and heard, preferring honesty over conflict.",
        idealPartnerMatch: "Someone who values emotional intelligence and can match your level of commitment.",
        growthAdvice: {
            forSelf: "Remember that your needs are just as important as the needs of those you love.",
            forRelationships: "Teach your partner how to love you; don't expect them to read your mind."
        },
        aiInsight: result.insight + " (Generated by LoveHue Intuition Engine)"
    };
}

async function generateInsights(answers) {
    const key = process.env.OPENAI_API_KEY;

    if (!key) {
        console.warn("No API Key found. Using Fallback Logic.");
        return generateFallbackProfile(answers);
    }

const prompt = `
You are a friendly and insightful Relationship Coach and Color Psychologist. Analyze the quiz answers to create a personalized "Love Hue" profile.

**TONE INSTRUCTION: Be warm, clear, and conversational.** - Avoid overly poetic, flowery, or abstract language. 
- Use plain English that is easy to understand. 
- Explain psychological concepts simply, as if explaining them to a friend over coffee.

**CORE INSTRUCTION: DO NOT SUMMARIZE.** Do not say "Because you chose X, you are Y." Instead, look for the *tension* between their answers. (e.g., If they value "Independence" but crave "Reassurance," analyze that conflict). Dig into the *why* and the *subconscious* implications of their choices.

**1. DETERMINE THEIR "LOVE HUE" (Color Psychology):**
   - **Hue (The Base):** Determine the emotional "temperature". Warm (Reds/Golds) = Passion/Action. Cool (Blues/Greens) = Peace/Logic. Purple/Indigo = Intuition/Depth.
   - **Saturation (The Intensity):** How intense are their needs? High saturation = intense, anxious, or passionate attachment. Low saturation (Pastels) = gentle, secure, or avoidant attachment.
   - **Brightness (The Energy):** Darker shades = depth, mystery, or protection. Lighter shades = openness, optimism, or vulnerability.
   - **Selection:** Generate a specific, evocative color name (e.g., "Stormy Teal," "Burnt Saffron," "Ethereal Lilac").

**2. PSYCHOLOGICAL ANALYSIS (The Depth):**
   - Identify their **Attachment Style** (Secure, Anxious, Avoidant, Disorganized) based on how they handle distance and conflict.
   - Identify their **Emotional dialect**: Do they speak in logic, sensation, service, or affirmations?

USER ANSWERS:
${JSON.stringify(answers, null, 2)}

**CRITICAL: RESPOND WITH ONLY A JSON OBJECT. NO MARKDOWN. NO PREAMBLE.**

{
  "loveProfile": "A poetic, narrative summary of their soul's approach to love. Synthesize their contradictions into a cohesive picture. Use 'You'.",
  "primaryLoveStyle": "Don't just name a love language. Explain the *psychological function* it serves for them (e.g., 'You use acts of service to create order in chaos').",
  "secondaryLoveStyle": "The subtle, often hidden way they show care that others might miss. Explain their 'quiet' love language.",
  "personalColor": {
      "hex": "A valid 6-character HEX code (e.g., #4A90E2) that matches the psychology above.",
      "name": "A creative, evocative name for this specific shade.",
      "meaning": "A deep analysis of WHY this color fits. Connect color theory (warmth/coolness) to their emotional data (intimacy/independence)."
  },
  "strengths": "The 'Superpowers' of their love style. What makes them a healing or exciting partner to be with?",
  "challenges": "The 'Shadow Side'. Bluntly but kindly identify their blind spots, fears of abandonment/engulfment, or tendency to shut down.",
  "communicationStyle": "Analyze how they encode and decode messages. Do they read between the lines? Do they need literalism? Do they withdraw?",
  "idealPartnerMatch": "Describe the specific energy that balances them (e.g., 'Someone who offers an anchor for your kite').",
  "growthAdvice": {
    "forSelf": "Actionable psychological advice for self-soothing or emotional regulation.",
    "forRelationships": "Actionable advice on how to bridge the gap between their intent and their impact on others."
  },
  "aiInsight": "A singular, beautiful metaphor that captures the essence of their heart (e.g., 'Your love is like a lighthouse...')."
}

**FINAL RULES:**
- **Address the user as "You" directly.**
- **NO REPETITION:** Do not restate the questions.
- **Keep it simple.** Avoid complex psychological jargon.
- **NO LISTS:** Use flowing, natural paragraphs.
- **DEPTH OVER BREADTH:** Focus on 2-3 profound insights rather than 10 shallow ones.
`;

try {
        console.log("Starting AI generation...");

        const timeoutPromise = new Promise((_, reject) => 
            setTimeout(() => reject(new Error("TIMEOUT")), 25000) 
        );


        const aiPromise = axios.post('https://openrouter.ai/api/v1/chat/completions',
        {
            model: "qwen/qwen3-max-thinking",
            messages: [{role: "user", content: prompt}],

        },
        {  
            headers: {
                Authorization: `Bearer ${key}`,
                "HTTP-Referer": "https://love-hue.vercel.app",
                "X-Title": "Love Hue"
            }
        }
    );

    const response = await Promise.race([aiPromise, timeoutPromise]);

        const text = response.data.choices?.[0]?.message?.content || "";
        const cleanJson = text.replace(/```json/g, '').replace(/```/g, '').trim();
        return JSON.parse(cleanJson);

    } catch (error) {
        if (error.message === "TIMEOUT") {
            console.warn("AI took too long. Switching to Fallback to save Vercel execution time.");
        } else {
            console.error("AI Error:", error.message);
        }
        
        return generateFallbackProfile(answers);
    }
} 

module.exports = { generateInsights } 